# Generated by Django 2.1.3 on 2018-11-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('modified_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('inactive', models.BooleanField(default=False, verbose_name='deleted')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'ordering': ('created_on', 'modified_on', 'inactive'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('modified_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('inactive', models.BooleanField(default=False, verbose_name='deleted')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'ordering': ('created_on', 'modified_on', 'inactive'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('modified_on', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
                ('inactive', models.BooleanField(default=False, verbose_name='deleted')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('popularity', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Popularity')),
                ('imdb_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='IMDB Score')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imdbapp.Director')),
                ('genre', models.ManyToManyField(to='imdbapp.Genre')),
            ],
            options={
                'ordering': ('created_on', 'modified_on', 'inactive'),
                'abstract': False,
            },
        ),
    ]
