# Generated by Django 2.1.3 on 2018-11-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='inactive',
            field=models.BooleanField(default=False, verbose_name='inactive'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='inactive',
            field=models.BooleanField(default=False, verbose_name='inactive'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='inactive',
            field=models.BooleanField(default=False, verbose_name='inactive'),
        ),
    ]
